version: "3.9"

services:
  web:
    build: .
    container_name: car_catalog_web
    ports:
      - "8080:80"       # сайт будет по http://localhost:8080
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: car_catalog_db
    environment:
      POSTGRES_DB: car_catalog
      POSTGRES_USER: caruser
        POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: car_catalog_adminer
    ports:
      - "8081:8080"     # панель управления БД: http://localhost:8081
    depends_on:
      - db

volumes:
  pgdata:
